/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Review = IDL.Record({
  'comment' : IDL.Text,
  'toolId' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllReviewsByTool' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getReview' : IDL.Func([IDL.Nat], [Review], ['query']),
  'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Review = IDL.Record({
    'comment' : IDL.Text,
    'toolId' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllReviewsByTool' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getReview' : IDL.Func([IDL.Nat], [Review], ['query']),
    'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };